name: Ansible Remediate Devel Pipeline Validation
'on':
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - devel
    paths:
    - '**.yml'
    - '**.sh'
    - '**.j2'
    - '**.ps1'
    - '**.cfg'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Congrats on opening your first pull request and thank you for
          taking the time to help improve Ansible-Lockdown!

          Please join in the conversation happening on the [Discord Server](https://www.lockdownenterprise.com/discord)
          as well.'
  build-azure-windows:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      WIN_USERNAME: ${{ secrets.WIN_USERNAME }}
      WIN_PASSWORD: ${{ secrets.WIN_PASSWORD }}
      OSVAR: ${{ vars.OSVAR }}
      TF_VAR_benchmark_type: ${{ vars.BENCHMARK_TYPE }}
      TF_VAR_repository: ${{ github.event.repository.name }}
      ANSIBLE_VERSION: ${{ vars.ANSIBLE_RUNNER_VERSION }}
      ENABLE_DEBUG: ${{ vars.ENABLE_DEBUG }}
    defaults:
      run:
        shell: bash
        working-directory: .github/workflows/github_windows_IaC
    steps:
    - name: Clone ${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: If a variable for IAC_BRANCH is set use that branch
      working-directory: .github/workflows
      run: "if [ ${{ vars.IAC_BRANCH }} != '' ]; then\n    echo \"IAC_BRANCH=${{ vars.IAC_BRANCH\
        \ }}\" >> $GITHUB_ENV\n    echo \"Pipeline using the following IAC branch\
        \ ${{ vars.IAC_BRANCH }}\"\nelse\n    echo IAC_BRANCH=main >> $GITHUB_ENV\n\
        fi\n"
    - name: Clone IaC Repository
      uses: actions/checkout@v4
      with:
        repository: ansible-lockdown/github_windows_IaC
        path: .github/workflows/github_windows_IaC
        ref: ${{ env.IAC_BRANCH }}
    - name: Save Sensitive Info
      run: echo "{\"username\":\"${WIN_USERNAME}\",\"password\":\"${WIN_PASSWORD}\"}"
        >> sensitive_info.json
    - name: DEBUG - Show IaC files
      if: env.ENABLE_DEBUG == 'true'
      run: 'echo "OSVAR = $OSVAR"

        echo "benchmark_type = $benchmark_type"

        pwd

        ls

        '
      env:
        OSVAR: ${{ vars.OSVAR }}
        TF_VAR_benchmark_type: ${{ vars.BENCHMARK_TYPE }}
    - name: Tofu init
      id: init
      run: tofu init
      env:
        OSVAR: ${{ vars.OSVAR }}
        TF_VAR_benchmark_type: ${{ vars.BENCHMARK_TYPE }}
    - name: Tofu validate
      id: validate
      run: tofu validate
      env:
        OSVAR: ${{ vars.OSVAR }}
        TF_VAR_benchmark_type: ${{ vars.BENCHMARK_TYPE }}
    - name: Tofo Apply
      id: apply
      env:
        WIN_USERNAME: ${{ secrets.WIN_USERNAME }}
        WIN_PASSWORD: ${{ secrets.WIN_PASSWORD }}
        OSVAR: ${{ vars.OSVAR }}
        TF_VAR_benchmark_type: ${{ vars.BENCHMARK_TYPE }}
      run: tofu apply -var-file "${OSVAR}.tfvars" --auto-approve -input=false
    - name: DEBUG - Show Ansible Hostfile
      if: env.ENABLE_DEBUG == 'true'
      run: cat hosts.yml
    - name: Run_Ansible_Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'
      run: '/opt/ansible_${{ env.ANSIBLE_VERSION }}_venv/bin/ansible-playbook -i hosts.yml
        ../../../site.yml

        '
    - name: Tofu Destroy
      if: always() && env.ENABLE_DEBUG == 'false'
      env:
        OSVAR: ${{ vars.OSVAR }}
        TF_VAR_benchmark_type: ${{ vars.BENCHMARK_TYPE }}
      run: tofu destroy -var-file "${OSVAR}.tfvars" --auto-approve
